program:
  overwrite: True

experiment:
  task: spacenet2
  name: spacenet2_test
  module:
    loss: "ce"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 3
    num_classes: 2
    ignore_zeros: True  # class 0 not used for scoring
  datamodule:
    root_dir: "data/spacenet2"
    image: "PS-RGB"
    collections: ["sn2_AOI_5_Khartoum"]
    batch_size: 2
    num_workers: 12
    seed: 42


trainer:
  gpus: 1
  min_epochs: 1
  max_epochs: 10
  log_every_n_steps: 2