program:
  seed: 0
  overwrite: True

trainer:
  gpus: 1
  min_epochs: 5
  max_epochs: 100
  auto_lr_find: False
  benchmark: True

experiment:
  task: "vhr10"
  name: "vhr10_test"
  module:
    detection_model: "faster-rcnn"
    backbone: "resnet50"
    pretrained: True
    num_classes: 11
    learning_rate: 1.3e-5
    learning_rate_schedule_patience: 6
    verbose: false
  datamodule:
    root: "data/vhr10"
    batch_size: 2
    patch_size: 512
    num_workers: 56
    val_split_pct: 0.2
